x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  op-geth:
    restart: "unless-stopped"
    build:
      context: ./op-geth
      dockerfile: Dockerfile.binary
      args:
        - DOCKER_TAG=${OPGETH_DOCKER_TAG}
    image: op-geth:${NETWORK}
    pull_policy: never
    stop_grace_period: 5m
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NETWORK=${NETWORK:-}
      - OPGETH_EXTRAS=${OPGETH_EXTRAS:-}
    volumes:
      - opgeth-data:/var/lib/op-geth
      - ./config:/var/lib/op-geth/config
      - jwtsecret:/var/lib/op-geth/ee-secret
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${OPGETH_P2P_PORT:-30303}:${OPGETH_P2P_PORT:-30303}/tcp
      - ${OPGETH_P2P_PORT:-30303}:${OPGETH_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - ${NETWORK}-geth # This allows multiple Worldchain Docker stacks all connected to the same central traefik
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --datadir
      - /var/lib/op-geth
      - --rollup.sequencerhttp
      - ${SEQUENCER}
      - --rollup.disabletxpoolgossip
      - --rollup.halt
      - major
      - --bootnodes
      - ${OPGETH_P2P_BOOTNODES}
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - "8551"
      - --authrpc.jwtsecret
      - /var/lib/op-geth/ee-secret/jwtsecret
      - --authrpc.vhosts=*
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${RPC_PORT:-8545}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8546}
      - --ws.origins=*
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr
      - 0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-bob}.service=${RPC_HOST:-bob}
      - traefik.http.routers.${RPC_HOST:-bob}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-bob}.rule=Host(`${RPC_HOST:-bob}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-bob}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-bob}lb.service=${RPC_HOST:-bob}
      - traefik.http.routers.${RPC_HOST:-bob}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-bob}lb.rule=Host(`${RPC_LB:-bob-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-bob}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-bob}.loadbalancer.server.port=${RPC_PORT:-8545}
      - traefik.http.routers.${WS_HOST:-bobws}.service=${WS_HOST:-bobws}
      - traefik.http.routers.${WS_HOST:-bobws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-bobws}.rule=Host(`${WS_HOST:-bobws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-bobws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-bobws}lb.service=${WS_HOST:-bobws}
      - traefik.http.routers.${WS_HOST:-bobws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-bobws}lb.rule=Host(`${WS_LB:-bobws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-bobws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-bobws}.loadbalancer.server.port=${WS_PORT:-8546}
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060
      - metrics.network=${NETWORK:-}
    
  op-node:
    restart: "unless-stopped"
    build:
      context: ./op-node
      dockerfile: Dockerfile.binary
      args:
        - DOCKER_TAG=${OPNODE_DOCKER_TAG}
    image: op-node:${NETWORK}
    pull_policy: never
    stop_grace_period: 1m
    stop_signal: SIGHUP
    environment:
      - OPNODE_EXTRAS=${OPNODE_EXTRAS}
    depends_on:
      - op-geth
    volumes:
      - jwtsecret:/var/lib/op-node/ee-secret
      - opnode-data:/var/lib/op-node
      - ./config:/var/lib/op-node/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${OPNODE_P2P_PORT:-9222}:${OPNODE_P2P_PORT:-9222}/tcp
      - ${OPNODE_P2P_PORT:-9222}:${OPNODE_P2P_PORT:-9222}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - op-node
      - --log.level
      - ${LOG_LEVEL}
      - --l2
      - ${L2_CONNECTION_KIND:-http}://${NETWORK}-geth:8551
      - --l2.jwt-secret
      - /var/lib/op-node/ee-secret/jwtsecret
      - --rollup.halt
      - major
      - --rollup.load-protocol-versions=true
      - --rollup.config
      - /var/lib/op-node/config/rollup.json
      - --l1
      - ${L1_RPC}
      - --l1.rpckind
      - ${L1_RPC_KIND:-basic}
      - --l1.beacon
      - ${L1_BEACON}
      - --rpc.addr
      - 0.0.0.0
      - --metrics.enabled
      - --p2p.listen.tcp
      - ${OPNODE_P2P_PORT:-9222}
      - --p2p.discovery.path
      - /var/lib/op-node/opnode_discovery_db
      - --p2p.peerstore.path
      - /var/lib/op-node/opnode_peerstore_db
      - --p2p.priv.path
      - /var/lib/op-node/opnode_p2p_priv.txt
      - --p2p.static
      - ${OPNODE_P2P_STATIC_PEERS}
      - --syncmode
      - execution-layer
      - --l1.trustrpc=true
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=7300
      - metrics.network=${NETWORK:-}

volumes:
  opgeth-data:
  opnode-data:
  jwtsecret:
